site_name: "ECO2 Guide Center"
site_url: https://verycoldplay.github.io/eco2_guide_center/
use_directory_urls: false

nav:
- Welcome to ECO2 Guide Center: index.md
- 1. ECO2 Logic Guide:
  - Overview: 1. ECO2 Logic Guide/index.md
  - ECO2 사용자 도움말:
      - ECO2 소개: 1. ECO2 Logic Guide/ECO2 사용자 도움말/ECO2_소개.md
      - 시작하기: 1. ECO2 Logic Guide/ECO2 사용자 도움말/시작하기.md
      - 데이터 입력: 1. ECO2 Logic Guide/ECO2 사용자 도움말/데이터_입력.md
      - 에너지 시뮬레이션: 1. ECO2 Logic Guide/ECO2 사용자 도움말/에너지_시뮬레이션.md

  - 냉방 에너지 분석:
      - 개요: 1. ECO2 Logic Guide/냉방 에너지 분석/개요.md
      - 냉방 부하 계산:
          - Simple Method: 1. ECO2 Logic Guide/냉방 에너지 분석/Simple_Method.md
      - 냉방 시스템 구성 요소: 1. ECO2 Logic Guide/냉방 에너지 분석/냉방_시스템_구성_요소.md
      - 결과 해석: 1. ECO2 Logic Guide/냉방 에너지 분석/결과_해석.md

  - 난방 에너지 분석: 1. ECO2 Logic Guide/난방_에너지_분석.md
  - 공조 시스템 분석: 1. ECO2 Logic Guide/공조_시스템_분석.md

  - 신재생에너지 시스템 분석:
      - 시뮬레이션 오류 해결 방법: 1. ECO2 Logic Guide/신재생에너지 시스템 분석/시뮬레이션_오류_해결_방법.md
      - 입력 데이터 오류 수정: 1. ECO2 Logic Guide/신재생에너지 시스템 분석/입력_데이터_오류_수정.md
      - 결과값 해석 관련 오류: 1. ECO2 Logic Guide/신재생에너지 시스템 분석/결과값_해석_관련_오류.md

  - 오류 및 경고 메시지: 1. ECO2 Logic Guide/오류_및_경고_메시지.md
  - 자주 묻는 질문 (FAQ): 1. ECO2 Logic Guide/자주_묻는_질문.md

  - 고급 기능:
      - 외피전개도 프로그램 연동: 1. ECO2 Logic Guide/고급 기능/외피전개도_프로그램_연동.md
      - IFC 모델 연동: 1. ECO2 Logic Guide/고급 기능/IFC_모델_연동.md

- 2. ECO2 User Guide:
  - Overview: ECO2_User_Guide/index.md

- 3. ECO2 Assessment Guide:
  - Overview: ECO2_Assessment_Guide/index.md

theme:
  name: material
  language: ko
  logo: assets/ECO2_icon.png

extra_css:
  - assets/pretendard.css
  - assets/custom.css

extra:
  eco2_title_1: 'ECO2 계산 원칙 및 로직 (Calculation Principles and Logic)'
  eco2_title_2: 'ECO2 계산 로직과 방법론 (Calculation Logic and Methodology)'
  eco2_title_3: 'ECO2 시뮬레이션 로직과 계산 원칙 (Simulation Logic and Calculation Principles)'
  eco2_title_4: 'ECO2 알고리즘 및 로직 가이드 (Algorithm and Logic Guide)'


extra_javascript:
#  - assets/mermaid-init.js  # mermaid 초기화 스크립트
  - assets/polyfill.min.js  # 로컬 경로로 polyfill.js 파일
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js
  - assets/mermaid-init.js
# https://unpkg.com/mermaid@10/dist/mermaid.min.js 

markdown_extensions:
  - attr_list  # 이 확장 기능이 있어야 { .class }가 작동합니다.
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2:
      javascript: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js


